proxy:
  # 代理类型: http, socks4, socks5
  # 使用 none 或其它值时不使用代理
  type: none
  # 代理地址
  host: '127.0.0.1'
  port: 8081
  # 代理账户验证，注释掉这两项为无账户验证
  # username: '123456'
  # password: '123456'

# 是否隐藏 IOException (大多是连接超时) 的异常堆栈跟踪日志
hide-stacktrace: false

# 每个正版账号最多能验证多少次
# 按正版账号 UUID 来识别
verify-times-limit: 1

# 每个玩家最多能尝试验证多少次
# 拥有 premiumverify.request.bypass-fail-limit 权限的玩家可无视失败次数限制
# 验证超时、网络问题 等不算做验证失败
# 正版账号超过最多验证次数、用户名不匹配 算作验证失败
fail-times-limit: 3

# 验证请求超时时间 (秒)
timeout: 300

# 拥有这个权限的玩家将同样被视为已通过验证
# 验证后插件不会给予玩家这个权限，但拥有这个权限的玩家将被视为已验证，不能再申请验证
# 将该选项设为空值关闭该功能
already-verified-permission: 'minecraft.account.premium'

# 正版验证奖励
# [console] 控制台命令
# [player] 玩家命令
# [message] 消息
# [broadcast] 全服公告
# [delay] 延时执行(单位为tick)，如 [delay] 20 会延时1秒
# 均支持使用 PAPI 变量
rewards:
  - '[message]&7[&b正版验证&7] &a你已完成正版验证!'
  - '[console]money give %player_name% 100'
