
# 每个正版账号最多能验证多少次
# 按正版账号 UUID 来识别
verify-times-limit: 1

# 每个玩家最多能尝试验证多少次
# 拥有 premiumverify.request.bypass-fail-limit 权限的玩家可无视失败次数限制
# 验证超时、网络问题 等不算做验证失败
# 正版账号超过最多验证次数、用户名不匹配 算作验证失败
fail-times-limit: 3

# 验证请求超时时间 (秒)
timeout: 300

# 拥有这个权限的玩家将同样被视为已通过验证
already-verified-permission: 'minecraft.premium'

# 正版验证奖励
# [console] 控制台命令
# [player] 玩家命令
# [message] 消息
# [broadcast] 全服公告
# [broadcast-bc] 全服公告 (通过BC广播，安装了该插件的子服都会公告)
# [delay] 延时执行(单位为tick)，如 [delay] 20 会延时1秒
# 均支持使用 PAPI 变量
rewards:
  - '[message]&7[&b正版验证&7] &a你已完成正版验证!'
  - '[console]money give %player_name% 100'

messages:
  help:
    - '&7[&b正版验证&7] &e正版验证 帮助'
    - '&7[&b正版验证&7] &f/pv request &e请求正版验证，最多可尝试3次'
  help-op:
    - '&7[&b正版验证&7] &e正版验证 帮助'
    - '&7[&b正版验证&7] &f/pv request &e请求正版验证，最多可尝试3次'
    - '&7[&b正版验证&7] &f/pv fail <玩家> <次数> &e设置玩家的失败次数'
    - '&7[&b正版验证&7] &f/pv reload &e重载配置文件'
  commands:
    reload: '&a配置文件已重载.'
    fail: '&a已设置 &e%player% &a的验证失败次数为 &e%times%.'
  error:
    only-player: '&7[&b正版验证&7] &e该命令仅能由玩家执行.'
    no-player: '&7[&b正版验证&7] &e无法找到该玩家.'
    no-integer: '&7[&b正版验证&7] &e你应该输入一个大于或等于0的整数.'
    fail-limit:
      - '&7[&b正版验证&7] &e你的账户已达到允许失败次数上限.'
    already-in-verify:
      - '&7[&b正版验证&7] &e你已经在验证中了.'
    already-verified:
      - '&7[&b正版验证&7] &a你已经进行过正版验证了.'
  verify-start:
    - '&7[&b正版验证&7] &e正在发起验证请求，请稍等…'
  verify:
    - '&f'
    - '&f'
    - '&f  请打开聊天栏，点击 %link% &f打开网页进行验证。'
    - '&f'
    - '&f  请在&e5分钟&f内完成验证。'
    - '&f  验证期间&b不要离开服务器&f，完成后你将获得奖励。'
    - '&f'
  link-text: '&7[&n&l验证网址&7]'
  link-hover:
    - '&e点击打开验证网址'
    - '&7如果需要输入代码，请使用 &f%code%'
  result-expired:
    - '&7[&b正版验证&7] &e你申请的验证已超时或过期.'
  result-not-match:
    - '&7[&b正版验证&7] &e用户名不正确，该正版账户的用户名是&b %name%&e，而你是&b %player%&e.'
  result-limit:
    - '&7[&b正版验证&7] &e该正版账户已到达可验证次数上限.'
