name: PremiumVerify
version: '${version}'
main: top.mrxiaom.premiumverify.Main
api-version: 1.13
softdepend:
  - PlaceholderAPI
authors: [ MrXiaoM ]
folia-supported: true
commands:
  premiumverify:
    description: Plugin Main Command
    aliases: [verify, pv]
